# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HB_Bruh' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
        pod 'SwiftConfettiView'
	pod 'R.swift'
  # Pods for HB_Bruh

end
